name: Testing

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.type }}
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { type: 'good', allow-failure: false }
          - { type: 'bad', allow-failure: true}
          - { type: 'ugly', allow-failure: false }
    env:
      type: ${{ matrix.type }}
    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      id: setup-ruby
      with:
        ruby-version: 3.2

    - name: Test
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: tests
      run: |
        if [ $type == "good" ]
        then
          echo "good"
          exit
        else
          echo $type
          exit 1
        fi

    # because continue-on-error marks the steps as pass even if they fail
    - name: "tests outcome: ${{ steps.tests.outcome }}"
      run: ""

  notify:
    uses: zzak/action-discord/.github/workflows/notify.yml@main
    if: always() && github.ref_name == 'test'
    needs: test
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    with:
      result: ${{ needs.test.result }}
